CREATE TABLE IF NOT EXISTS `tblGeneral` (
  `id` INT NOT NULL,
  `generalSiteName` VARCHAR(1000) NOT NULL,
  `generalRainfall` DECIMAL(5,1),
  `generalHumidity` DECIMAL(4,1),
  `generalSolarRad` DECIMAL(2,1),
  `lat` DECIMAL(10,2) NOT NULL,
  `long` DECIMAL(11,2) NOT NULL,
  `airTemp` DECIMAL(5,1),
  `airWindSpeed` DECIMAL(5,2),
  `airWindDirection` DECIMAL(4,1),
  `airQuality25` DECIMAL(5,1),
  `airGustSpeed` DECIMAL(5,2),
  `airQuality10` DECIMAL(5,2),
  `waterFlowrate` DECIMAL(1,1),
  `waterTemp` DECIMAL(5,1),
  `turbidity` DECIMAL(4,3),
  `e_coli` INT,
  `enterococci` DECIMAL(4,3),
  `chlorophyll_a_calc` DECIMAL(4,3),
  `periphyton_chlorophyll_a` DECIMAL(4,3),
  `black_disc` INT,
  `ammoniacal_nitrogen` DECIMAL(4,3),
  `nitrite_nitrogen` INT,
  `total_nitrogen` INT,
  `total_kjeldahl_nitrogen` DECIMAL(4,3),
  `total_phosphorus` DECIMAL(3,2),
  `dissolved_reactive_phosphorus` INT,
  PRIMARY KEY (`id`));
